import * as React from "react";
import { motion, useReducedMotion } from "framer-motion";
import { ToolLayout } from "@/layouts/ToolLayout";
import { OutputBlock } from "@/components/ui/OutputBlock";
import { OutputBlockSkeleton } from "@/components/ui/Skeleton";
import { CopyButton } from "@/components/ui/CopyButton";
import { Button } from "@/components/ui/button";
import { RefreshCw } from "lucide-react";
import { toBase64Url } from "@/utils/encoding";
import type { FAQItem } from "@/components/FAQSection";

const FAQ_ITEMS: FAQItem[] = [
  {
    question: "What is VAPID?",
    answer:
      "VAPID (Voluntary Application Server Identification) is a mechanism defined in RFC 8292 that allows web push notification servers to identify themselves to push services (like FCM, APNs). It uses an ECDH P-256 key pair: the public key is shared with the browser as the applicationServerKey, and the private key signs JWT tokens that authenticate push requests.",
  },
  {
    question: "How do I use these keys with web-push?",
    answer:
      "In Node.js with the web-push library: const webpush = require('web-push'); webpush.setVapidDetails('mailto:you@example.com', publicKey, privateKey). Pass the public key to navigator.serviceWorker.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: publicKey }) in your frontend code.",
  },
  {
    question: "Are VAPID keys the same as push subscription keys?",
    answer:
      "No. VAPID keys identify your server. Push subscription keys (p256dh and auth) are generated by the browser for each subscription and are used to encrypt the notification payload. VAPID keys are used to authenticate your server's identity with the push service.",
  },
  {
    question: "How often should I rotate VAPID keys?",
    answer:
      "Rotating VAPID keys invalidates all existing push subscriptions — all users must re-subscribe. Rotate only if your private key is compromised. Unlike session keys, VAPID keys are meant to be long-lived per deployment.",
  },
];

interface VapidKeyPair {
  publicKey: string;
  privateKey: string;
}

async function generateVapidKeys(): Promise<VapidKeyPair> {
  const keyPair = await crypto.subtle.generateKey(
    { name: "ECDH", namedCurve: "P-256" },
    true,
    ["deriveKey"]
  );

  const [publicKeyBuffer, privateKeyBuffer] = await Promise.all([
    crypto.subtle.exportKey("raw", keyPair.publicKey),
    crypto.subtle.exportKey("pkcs8", keyPair.privateKey),
  ]);

  return {
    publicKey: toBase64Url(new Uint8Array(publicKeyBuffer)),
    privateKey: toBase64Url(new Uint8Array(privateKeyBuffer)),
  };
}

export default function VapidKeyPage(): React.JSX.Element {
  const prefersReducedMotion = useReducedMotion();
  const [keys, setKeys] = React.useState<VapidKeyPair | null>(null);
  const [isGenerating, setIsGenerating] = React.useState(false);

  const generate = React.useCallback(async () => {
    setIsGenerating(true);
    try {
      const result = await generateVapidKeys();
      setKeys(result);
    } finally {
      setIsGenerating(false);
    }
  }, []);

  React.useEffect(() => {
    void generate();
  }, [generate]);

  return (
    <ToolLayout
      toolId="vapid-key"
      faqItems={FAQ_ITEMS}
      relatedToolIds={["ssh-key", "wireguard-key", "api-key"]}
      securityNotes="The VAPID private key must remain secret on your server. The public key is safe to embed in client-side JavaScript as the applicationServerKey."
    >
      <motion.div
        initial={prefersReducedMotion ? false : { opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.25 }}
        className="space-y-6"
      >
        <section
          aria-label="VAPID key generator"
          className="rounded-lg border bg-card p-5 shadow-sm space-y-5 sm:p-6"
        >
          {isGenerating || !keys ? (
            <div className="space-y-4">
              <OutputBlockSkeleton />
              <OutputBlockSkeleton />
            </div>
          ) : (
            <div className="space-y-5">
              <div>
                <div className="mb-1.5 flex items-center justify-between">
                  <p className="text-sm font-medium text-foreground">Public Key (applicationServerKey)</p>
                  <CopyButton value={keys.publicKey} size="sm" label="Copy" />
                </div>
                <OutputBlock value={keys.publicKey} aria-label="VAPID public key" />
                <p className="mt-1 text-xs text-muted-foreground">
                  Pass to <span className="font-mono">pushManager.subscribe(&#123; applicationServerKey: ... &#125;)</span>
                </p>
              </div>

              <div>
                <div className="mb-1.5 flex items-center justify-between">
                  <p className="text-sm font-medium text-foreground">Private Key</p>
                  <CopyButton value={keys.privateKey} size="sm" label="Copy" />
                </div>
                <OutputBlock value={keys.privateKey} aria-label="VAPID private key" />
                <p className="mt-1 text-xs text-muted-foreground">
                  Pass to <span className="font-mono">webpush.setVapidDetails()</span> on your server. Keep secret.
                </p>
              </div>

              <Button variant="outline" onClick={() => void generate()} className="gap-2">
                <RefreshCw className="h-4 w-4" aria-hidden="true" />
                Regenerate key pair
              </Button>
            </div>
          )}
        </section>
      </motion.div>
    </ToolLayout>
  );
}
